name: Java CI

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - uses: jfrog/setup-jfrog-cli@v1
      - run: |
           mkdir staging
           mkdir staging/${{github.ref_name}}
           cp target/*.jar staging/${{github.ref_name}}/.
           jfrog rt u "staging/*.jar" akeyless-java-cloudid/io/akeyless/cloudid/  --url=https://akeyless.jfrog.io/artifactory --user=ci-user --password=${{ secrets.ARTIFACTORY_ACCESS_KEY }}