name: Java CI
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        env:
          VER: ${{github.ref_name}}
        run: mvn --batch-mode --update-snapshots verify
      - uses: jfrog/setup-jfrog-cli@v1
      - run: |
           mkdir ${{github.ref_name}}
           cp target/*.jar ${{github.ref_name}}/.
           jfrog rt u "${{github.ref_name}}/*-jar-with-dependencies.jar" akeyless-java/io/akeyless/cloudid/${{github.ref_name}}/akeyless-cloudid-${{github.ref_name}}.jar  --url=https://akeyless.jfrog.io/artifactory --user=ci-user --password=${{ secrets.ARTIFACTORY_ACCESS_KEY }}